name: sd-next
services:
  webui:
    build:
      args:
        BASE_IMG: nvidia/cuda:12.5.0-runtime-ubuntu22.04
      context: .
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
            count: all
    environment:
      SD_DATADIR: /data
    ports:
    - 7860:7860
    stdin_open: true
    tty: true
    volumes:
    - SD-Next:/data
volumes:
  SD-Next: null
