name: Issue Report
description: Something is broken in the core app
title: "[Issue]: "
labels: []

body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us what happened in a very clear and simple way
      value: Please fill this form with as much information as possible
  - type: textarea
    id: platform
    attributes:
      label: Version Platform Description
      description: Describe your platform (program version, OS, browser)
      value: 
  - type: markdown
    attributes:
      value: |
        Any issues without version information will be closed  
        Provide any relevant platorm information:  
        - Application version, OS details, GPU information, browser used  
        
        Easiest is to include top part of console log, for example:  
        ```log
        Starting SD.Next
        Version: app=sd.next updated=2024-06-28 hash=1fc20e72 branch=dev url=https://github.com/vladmandic/automatic/tree/dev ui=dev
        Branch sync failed: sdnext=dev ui=dev
        Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.153.1-microsoft-standard-WSL2 python=3.12.3
        Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
        Load packages: {'torch': '2.3.1+cu121', 'diffusers': '0.29.1', 'gradio': '3.43.2'}
        Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
        Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8902 driver=555.99
        Extensions: enabled=['sd-webui-agent-scheduler', 'sd-extension-chainner', 'sd-extension-system-info', 'sdnext-modernui', 'Lora'] extensions-builtin
        Extensions: enabled=[] extensions
        ```
  - type: markdown
    attributes:
      value: |
        Please follow these guidelines when creating an issue:  
        - If issue is related to ModernUI, create issue at [ModernUI issues](https://github.com/BinaryQuantumSoul/sdnext-modernui/issues)
        - If possible update to latest version before reporting the issue as older versions cannot be properly supported  
          And search existing **issues** and **discussions** before creating a new one  
        - If issue cannot be clearly seen in the provided log, run SD.Next with debug logging enabled by adding `--debug` to your command line parameters
        - If issue is setup, installation or startup related, please check `sdnext.log` before reporting  
          And if possible, perform reinstallation of required dependencies by running SD.Next with `--reinstall` command line flag  
        - If issue is after recent update of SD.Next, try to reproduce it using clean installation to avoid issues due to old configuration  
        - If you have additional extensions installed, try to reproduce the issue with user extensions disabled  
          And if the issue is with compatibility with specific extension, mark it as such when creating the issue  
          Try running with `--safe` command line flag with disables loading of user-installed extensions  
        - If issue is in functionality marked as *experimental* or relates to *dev* branch, reach out on Discord before creating an issue  
          To see which issues are new/updated/experimental, check [CHANGELOG](https://github.com/vladmandic/automatic/blob/master/CHANGELOG.md)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    attributes:
      value: |
        If unsure if this is a right place to ask your question, perhaps post on [Discussions](https://github.com/vladmandic/automatic/discussions)
        Or reach-out to us on [Discord](https://discord.gg/WqMzTUDC)
  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: What is the backend you're using?
      options:
        - Diffusers
        - Original
      default: 0
    validations:
      required: true
  - type: dropdown
    id: ui
    attributes:
      label: UI
      description: Which UI are you're using?
      options:
        - API
        - Standard
        - ModernUI
      default: 1
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: What is the branch you're using?
      options:
        - Master
        - Dev
      default: 0
    validations:
      required: true
  - type: dropdown
    id: model
    attributes:
      label: Model
      description: What is the model type you're using?
      options:
        - StableDiffusion 1.5
        - StableDiffusion 2.1
        - StableDiffusion XL
        - StableDiffusion 3.x
        - StableCascade
        - FLUX.1
        - PixArt
        - Kandinsky
        - Playground
        - AuraFlow
        - Any Video Model
        - Other
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Acknowledgements
      description: 
      options:
        - label: I have read the above and searched for existing issues
          required: true
        - label: I confirm that this is classified correctly and its not an extension issue
          required: true
